-- AUTO-GENERATED seed data (SQLite). Sinh bởi work/gen_seed.py
PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

-- Users (tài khoản demo, mật khẩu '123456' được hash khi init DB)
INSERT INTO Users (name, phone, password_hash, address, cooperative_name, role) VALUES ('Nguyễn Văn An', '0900000001', '__SEED_PW__', 'Tỉnh Hòa Bình', 'Vườn Trái Cây Cao Phong', 'seller');
INSERT INTO Users (name, phone, password_hash, address, cooperative_name, role) VALUES ('Trần Thị Mai', '0900000002', '__SEED_PW__', 'Tỉnh Bình Thuận', 'Nông Sản Phương Nam', 'seller');
INSERT INTO Users (name, phone, password_hash, address, cooperative_name, role) VALUES ('Phạm Thị Hương', '0900000003', '__SEED_PW__', 'Tỉnh Lâm Đồng', 'Nông Trại Đà Lạt Xanh', 'seller');
INSERT INTO Users (name, phone, password_hash, address, cooperative_name, role) VALUES ('Lê Văn Hùng', '0900000004', '__SEED_PW__', 'Tỉnh Sóc Trăng', 'Đặc Sản Mekong', 'seller');
INSERT INTO Users (name, phone, password_hash, address, cooperative_name, role) VALUES ('Y Blơm Niê', '0900000005', '__SEED_PW__', 'Tỉnh Đắk Lắk', 'Hương Vị Tây Nguyên', 'seller');
INSERT INTO Users (name, phone, password_hash, address, cooperative_name, role) VALUES ('Người Mua Demo', '0911111111', '__SEED_PW__', 'TP. Hồ Chí Minh', NULL, 'buyer');
INSERT INTO Users (name, phone, password_hash, address, cooperative_name, role) VALUES ('Quản Trị Viên', '0999999999', '__SEED_PW__', 'TP. Hà Nội', NULL, 'admin');

-- Market_Prices
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Cam sành', 'VietGAP', 'Hòa Bình', 'kg', 18000, 28000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Bưởi', 'VietGAP', 'Phú Thọ', 'kg', 45000, 70000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Thanh long', 'VietGAP', 'Bình Thuận', 'kg', 20000, 35000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Xoài', 'VietGAP', 'Tiền Giang', 'kg', 40000, 65000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Rau xà lách', 'Organic Certified', 'Lâm Đồng', 'kg', 25000, 40000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Khoai lang', 'Hữu cơ', 'Vĩnh Long', 'kg', 18000, 30000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Măng tây', 'VietGAP', 'Ninh Thuận', 'kg', 60000, 90000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Gạo ST25', 'VietGAP', 'Sóc Trăng', 'kg', 32000, 48000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Mè đen', 'Tự nhiên', 'An Giang', 'kg', 80000, 110000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Tiêu đen', 'Chỉ dẫn địa lý', 'Kiên Giang', 'kg', 150000, 200000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Sả', 'Tự nhiên', 'Đồng Nai', 'kg', 25000, 45000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Nhãn', 'Truyền thống', 'Hưng Yên', 'kg', 120000, 160000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Nho khô', 'Tự nhiên', 'Ninh Thuận', 'kg', 70000, 100000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Lúa', 'VietGAP', 'Đồng bằng sông Cửu Long', 'kg', 7000, 12000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Cà phê Robusta', 'Tự nhiên', 'Đắk Lắk', 'kg', 90000, 130000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Cà phê Arabica', 'Tự nhiên', 'Lâm Đồng', 'kg', 150000, 220000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Sầu riêng', 'VietGAP', 'Tiền Giang', 'kg', 55000, 95000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Hồ tiêu', 'Chỉ dẫn địa lý', 'Kiên Giang', 'kg', 150000, 200000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Điều', 'Tự nhiên', 'Bình Phước', 'kg', 180000, 260000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Vải thiều', 'VietGAP', 'Bắc Giang', 'kg', 25000, 45000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Dưa hấu', 'Tự nhiên', 'Long An', 'kg', 8000, 15000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Mít Thái', 'VietGAP', 'Đồng Nai', 'kg', 15000, 30000);
INSERT INTO Market_Prices (product_name, standard, region, unit, min_price, max_price) VALUES ('Bơ', 'Tự nhiên', 'Đắk Lắk', 'kg', 30000, 55000);

-- Products (id khớp với frontend để link chatbot -> /product/{id})
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (1, 1, 1, 'fruits', 'Cam Cao Phong', 'Hữu cơ', 100, 'kg', 22000, 'https://cdn.tgdd.vn/2024/10/CookRecipe/CookTipsNote/cam-cao-phong-la-cam-gi-nhung-mon-ngon-tu-cam-cao-phong-tipsnote-800x500.jpg', 'active', 4.8, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (2, 1, 2, 'fruits', 'Bưởi Đoan Hùng', 'VietGAP', 35, 'kg', 60000, 'https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?w=400&q=80', 'active', 4.7, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (3, 2, 3, 'fruits', 'Thanh Long Ruột Đỏ', 'VietGAP', 120, 'kg', 45000, 'https://images.unsplash.com/photo-1527325678964-54921661f888?w=400&q=80', 'active', 4.6, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (4, 2, 4, 'fruits', 'Xoài Cát Tiền Giang', 'VietGAP', 0, 'kg', 55000, 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&q=80', 'active', 4.9, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (5, 3, 5, 'vegetables', 'Rau Xà Lách Baby Đà Lạt', 'Organic Certified', 92, 'gói 250g', 35000, 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&q=80', 'active', 4.7, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (6, 4, 6, 'vegetables', 'Khoai Lang Tím Hữu Cơ', 'Hữu cơ', 67, 'kg', 28000, 'https://images.unsplash.com/photo-1579384264577-79580c9d3a36?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cHVycGxlJTIwc3dlZXQlMjBwb3RhdG9lc3xlbnwwfHwwfHx8MA%3D%3D', 'active', 4.5, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (7, 3, 7, 'vegetables', 'Măng Tây Xanh Ninh Thuận', 'Organic Certified', 200, 'bó 500g', 72000, 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&q=80', 'active', 4.8, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (8, 4, 8, 'grains', 'Gạo ST25 Đặc Sản', 'VietGAP', 15, 'kg', 42000, 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&q=80', 'active', 5, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (9, 4, 9, 'grains', 'Mè Đen An Giang', 'VietGAP', 43, '500g', 95000, 'https://images.unsplash.com/photo-1563117063-ad38230557bc?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'active', 4.6, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (10, 5, 10, 'herbs', 'Tiêu Đen Phú Quốc', 'Tự nhiên', 88, '250g', 180000, 'https://images.unsplash.com/photo-1652128288742-df890f000a56?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmxhY2slMjBwZXBwZXJ8ZW58MHx8MHx8fDA%3D', 'active', 4.9, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (11, 5, 11, 'herbs', 'Sả Khô Đồng Nai', 'Tự nhiên', 156, '200g', 38000, 'https://media.istockphoto.com/id/126224019/photo/lemon-grass-as-spice-from-india.webp?a=1&b=1&s=612x612&w=0&k=20&c=BBfEJoUlLI8fyVR2zoqJyaPOtown2FXttc6tDGZa6TM=', 'active', 4.4, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (12, 1, 12, 'dried', 'Nhãn Lồng Sấy Hưng Yên', 'VietGAP', 74, '500g', 145000, 'https://plus.unsplash.com/premium_photo-1676879545004-01038cde2520?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZHJ5JTIwbG9uZ2FufGVufDB8fDB8fHww', 'active', 4.7, 0);
INSERT INTO Products (id, seller_id, market_price_id, category, name, standard, quantity, unit, price, image_url, status, rating, is_deleted) VALUES (13, 2, 13, 'dried', 'Nho Khô Ninh Thuận', 'VietGAP', 9, '300g', 88000, 'https://plus.unsplash.com/premium_photo-1669205434519-a042ba09fbdd?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8ZHJ5JTIwZ3JhcGV8ZW58MHx8MHx8fDA%3D', 'active', 4.5, 0);

-- Crop_Knowledge (RAG)
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Lúa', 'Cây lương thực chủ lực của Việt Nam, trồng nhiều ở ĐBSCL và ĐB sông Hồng.', 'Làm đất kỹ, bón lót lân; giữ mực nước 3-5cm giai đoạn đẻ nhánh; phòng đạo ôn, rầy nâu; bón cân đối NPK theo 3 giảm 3 tăng.', 'Phơi khô đến độ ẩm 13-14%, bảo quản nơi khô thoáng, tránh mọt.', 'Đồng bằng sông Cửu Long, Đồng bằng sông Hồng', 'Vụ Đông Xuân (2-4), Hè Thu (7-9)', 'VietGAP');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Cà phê Robusta', 'Cà phê vối, chịu nóng tốt, chiếm phần lớn sản lượng Tây Nguyên.', 'Trồng nơi đủ nắng, tưới đủ mùa khô; tỉa cành tạo tán; bón phân sau thu hoạch; phòng rệp sáp và bệnh gỉ sắt.', 'Phơi/sấy hạt đến độ ẩm 12-13%, bảo quản trong bao kín, nơi khô ráo.', 'Đắk Lắk, Gia Lai, Đắk Nông, Lâm Đồng', 'Thu hoạch tháng 10-12', 'Tự nhiên');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Cà phê Arabica', 'Cà phê chè, hương vị tinh tế, thích hợp vùng cao mát.', 'Trồng độ cao trên 1000m, cần che bóng; phòng sâu đục thân và bệnh khô cành; thu hái quả chín đỏ.', 'Sơ chế ướt hoặc honey, phơi đều, bảo quản kín tránh ẩm mốc.', 'Lâm Đồng (Cầu Đất), Sơn La, Điện Biên', 'Thu hoạch tháng 11-1', 'Tự nhiên');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Cam sành', 'Cây có múi giàu vitamin C, vỏ dày, nhiều nước.', 'Trồng đất thoát nước tốt; bón phân hữu cơ; phòng sâu vẽ bùa, bệnh vàng lá greening; tỉa cành thông thoáng.', 'Bảo quản nơi mát 8-10°C, tránh dập, dùng trong 2-3 tuần.', 'Hòa Bình, Hà Giang, Vĩnh Long', 'Thu hoạch tháng 10-12', 'VietGAP');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Xoài', 'Cây ăn quả nhiệt đới, giống Cát Hòa Lộc, Cát Chu nổi tiếng.', 'Bao trái chống ruồi đục quả; bón kali giai đoạn nuôi quả; phòng thán thư, rầy bông xoài.', 'Thu hái khi quả già, ủ chín tự nhiên; bảo quản 10-13°C.', 'Tiền Giang, Đồng Tháp, An Giang', 'Thu hoạch tháng 3-6', 'VietGAP');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Sầu riêng', 'Cây ăn quả giá trị cao, giống Ri6, Monthong (Dona).', 'Quản lý nước nghiêm ngặt giai đoạn ra hoa; tỉa hoa tỉa trái; phòng bệnh xì mủ, nứt thân do Phytophthora.', 'Thu hoạch đúng độ chín (gõ kêu bộp); cấp đông múi nếu cần để lâu.', 'Tiền Giang, Đắk Lắk, Lâm Đồng', 'Thu hoạch tháng 5-8', 'VietGAP');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Thanh long', 'Cây thuộc họ xương rồng, ruột trắng/đỏ, giàu chất chống oxy hóa.', 'Làm trụ cho cây leo; chong đèn kích ra hoa trái vụ; phòng bệnh đốm nâu (nấm Neoscytalidium).', 'Bảo quản lạnh 5°C, giữ tươi 2-3 tuần.', 'Bình Thuận, Long An, Tiền Giang', 'Thu hoạch quanh năm (chính vụ 5-8)', 'VietGAP');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Hồ tiêu', 'Cây gia vị xuất khẩu chủ lực, hạt tiêu đen/tiêu trắng.', 'Trồng trên trụ sống/trụ chết; thoát nước tốt tránh chết nhanh chết chậm; bón hữu cơ vi sinh.', 'Phơi khô đến độ ẩm dưới 13%, bảo quản kín, tránh hút ẩm.', 'Kiên Giang (Phú Quốc), Đắk Lắk, Gia Lai, Bình Phước', 'Thu hoạch tháng 1-4', 'Chỉ dẫn địa lý');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Điều', 'Cây công nghiệp lấy hạt, Bình Phước là thủ phủ.', 'Trồng đất dốc thoát nước; tỉa cành tạo tán; phòng bọ xít muỗi và bệnh thán thư giai đoạn ra hoa.', 'Phơi khô hạt, bảo quản nơi thoáng tránh ẩm mốc Aflatoxin.', 'Bình Phước, Đồng Nai, Bà Rịa-Vũng Tàu', 'Thu hoạch tháng 2-4', 'Tự nhiên');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Vải thiều', 'Cây ăn quả đặc sản miền Bắc, nổi tiếng Lục Ngạn.', 'Khoanh cành kích ra hoa; tưới đủ giai đoạn nuôi quả; phòng sâu đục cuống và bọ xít.', 'Xử lý lạnh nhanh sau thu hoạch; bảo quản 4-5°C để giữ màu vỏ.', 'Bắc Giang (Lục Ngạn), Hải Dương (Thanh Hà)', 'Thu hoạch tháng 5-7', 'VietGAP');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Nhãn', 'Cây ăn quả á nhiệt đới, nhãn lồng Hưng Yên ngọt đậm.', 'Tỉa cành sau thu hoạch; xử lý ra hoa; phòng bọ xít, sâu đục quả; bón kali nuôi cùi.', 'Sấy long nhãn hoặc bảo quản lạnh; nhãn sấy giữ nơi khô kín.', 'Hưng Yên, Sơn La, ĐBSCL', 'Thu hoạch tháng 7-9', 'Truyền thống');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Dưa hấu', 'Cây dưa ngắn ngày, ruột đỏ ngọt mát.', 'Trồng luống cao phủ bạt; thụ phấn bổ sung; định trái; phòng bệnh héo rũ và nứt quả do tưới không đều.', 'Bảo quản nơi thoáng mát, tránh nắng trực tiếp; dùng trong 1-2 tuần.', 'Long An, Tiền Giang, Quảng Ngãi', 'Thu hoạch quanh năm', 'Tự nhiên');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Khoai lang', 'Cây lấy củ, giống khoai tím Nhật, mật Đà Lạt.', 'Trồng đất tơi xốp thoát nước; vun luống; phòng sùng (bọ hà) khoai lang; hạn chế đạm cuối vụ.', 'Hong khô vỏ, bảo quản nơi khô thoáng, tránh mọc mầm.', 'Vĩnh Long, Đắk Nông, Gia Lai', 'Thu hoạch sau 4-5 tháng', 'Hữu cơ');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Mít Thái', 'Cây ăn quả cho năng suất cao, múi giòn ngọt.', 'Tỉa trái để trái to đều; bao trái; phòng sâu đục trái và xơ đen; thoát nước tốt.', 'Tách múi cấp đông để xuất khẩu; quả nguyên bảo quản nơi mát.', 'Đồng Nai, Tiền Giang, Đắk Lắk', 'Thu hoạch quanh năm', 'VietGAP');
INSERT INTO Crop_Knowledge (crop_name, description, care_tips, storage_tips, growing_regions, harvest_months, popular_standard) VALUES ('Bơ', 'Cây ăn quả giàu chất béo tốt, giống bơ 034, bơ sáp.', 'Trồng nơi thoát nước; tạo tán; phòng bệnh thối rễ Phytophthora; thu hái khi quả đạt độ già.', 'Ủ chín tự nhiên sau thu hoạch; bảo quản mát để kéo dài.', 'Đắk Lắk, Lâm Đồng, Đắk Nông', 'Thu hoạch tháng 5-9', 'Tự nhiên');

COMMIT;
